AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/**/*
    - bin/*
  DisplayCopNames: true
  DisplayStyleGuide: true

LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true
