AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/**/*
    - bin/*
  RunRailsCops: true
  DisplayCopNames: true
  DisplayStyleGuide: true

LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15